name: Compile BW16 Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python-is-python3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Core and Compile
        run: |
          URL="https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek_amebad_index.json"
          
          arduino-cli core update-index --additional-urls "$URL"
          arduino-cli core install realtek:AmebaD --additional-urls "$URL"
          arduino-cli lib install "Adafruit GFX Library" "Adafruit SSD1306"

          mkdir -p BW16
          cp * BW16/ 2>/dev/null || true

          # Автоматичний пошук точного FQBN для BW16
          FQBN=$(arduino-cli board listall --additional-urls "$URL" | grep -i "BW16" | awk '{print $NF}' | tail -n 1)
          echo "Знайдено FQBN: $FQBN"

          mkdir -p ./build
          arduino-cli compile --fqbn "$FQBN" --additional-urls "$URL" --output-dir ./build BW16

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BW16-Firmware
          path: ./build/
