name: Compile BW16 Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Prepare Sketch Directory and Compile
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek_amebad_index.json
          arduino-cli core update-index
          arduino-cli core install realtek:amebad@3.0.8
          arduino-cli lib install "Adafruit GFX Library" "Adafruit SSD1306"
          
          # Знаходимо перший .ino файл у репозиторії
          INO_FILE=$(ls *.ino | head -n 1)
          SKETCH_NAME="${INO_FILE%.ino}"
          
          echo "Знайдено скетч: $SKETCH_NAME"
          
          # Створюємо папку під вимоги arduino-cli та переносимо туди всі файли
          mkdir -p "$SKETCH_NAME"
          cp * "$SKETCH_NAME/" 2>/dev/null || true
          
          # Компілюємо зкетч з створеної папки
          arduino-cli compile --fqbn realtek:amebad:BW16 --output-dir ./build "$SKETCH_NAME"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BW16-Firmware
          path: ./build/*.bin
